// <auto-generated />
namespace EtnaPOS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class zatvaranjeDana2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zatvaranjeDana2));
        
        string IMigrationMetadata.Id
        {
            get { return "202206072125502_zatvaranjeDana2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
